/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

int *
add_1_svc(intpair *argp, struct svc_req *rqstp)
{

	static int  result;
	printf("add function called with a=%d b=%d.\n", argp->a, argp->b);
	result = argp->a + argp->b;
	printf("add function called with a=%d b=%d. returned=%d\n", argp->a, argp->b, result);
	return(&result);
}
